version: 1.0.{build}

image: Visual Studio 2022

environment:
  RDP_USER: BulletTemp
  RDP_PASS: Bullet@12345
  TS_TAILNET: yourname@gmail.com        # 👈 change this
  TS_API_KEY: your_tailscale_api_key    # 👈 change this
  TS_AUTHKEY: your_tailscale_auth_key   # 👈 change this
  CRD_CODE: ""                          # optional Chrome Remote Desktop code
  CRD_PIN: "123456"
  RUNTIME_MINUTES: 55                   # runtime (AppVeyor max ~60min)

init:
  - ps: Write-Host "🚀 Starting AppVeyor RDP setup..."

install:
  - ps: |
      Write-Host "📦 Installing Tailscale..."
      $url = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
      $dst = "$env:TEMP\tailscale.msi"
      Invoke-WebRequest -Uri $url -OutFile $dst
      Start-Process msiexec.exe -ArgumentList "/i","`"$dst`"","/quiet","/norestart" -Wait
      Remove-Item $dst -Force

      & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey "$env:TS_AUTHKEY" --hostname "bullet" --accept-dns=true --accept-routes=true
      $ip4 = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4 | Select-Object -First 1
      Write-Host "✅ Tailscale IPv4: $ip4"

  - ps: |
      Write-Host "🪟 Enabling RDP access..."
      $u=$env:RDP_USER; $p=$env:RDP_PASS
      $sec = ConvertTo-SecureString $p -AsPlainText -Force
      if (-not (Get-LocalUser -Name $u -EA SilentlyContinue)) {
        New-LocalUser -Name $u -Password $sec -AccountNeverExpires
        Add-LocalGroupMember -Group "Administrators" -Member $u
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $u
      }
      Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
      Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      Write-Host "✅ RDP ready — User=$u  Pass=$p  IP=$ip4"

  - ps: |
      Write-Host "🔧 Installing RustDesk..."
      $rdUrl = "https://github.com/rustdesk/rustdesk/releases/download/1.3.1/rustdesk-1.3.1-x86_64.msi"
      $rdDst = "$env:TEMP\rustdesk.msi"
      Invoke-WebRequest -Uri $rdUrl -OutFile $rdDst
      Start-Process msiexec.exe -ArgumentList "/i","`"$rdDst`"","/quiet","/norestart" -Wait
      Remove-Item $rdDst -Force
      Write-Host "✅ RustDesk installed"

      # Open ports for RustDesk
      for ($p=21115; $p -le 21119; $p++) {
        netsh advfirewall firewall add rule name="RUSTDESK-TCP-$p" dir=in action=allow protocol=TCP localport=$p | Out-Null
      }
      netsh advfirewall firewall add rule name="RUSTDESK-UDP-21116" dir=in action=allow protocol=UDP localport=21116 | Out-Null

  - ps: |
      Write-Host "🎯 Starting RustDesk..."
      Start-Process "C:\Program Files\RustDesk\rustdesk.exe"
      Start-Sleep -Seconds 5
      Write-Host "✅ RustDesk running."

build_script:
  - ps: |
      $mins = [int]$env:RUNTIME_MINUTES
      Write-Host "⏳ Keeping VM alive for $mins minutes..."
      $end = (Get-Date).AddMinutes($mins)
      while ((Get-Date) -lt $end) {
        Write-Host ("💓 Heartbeat at " + (Get-Date).ToString("HH:mm:ss"))
        Start-Sleep -Seconds 60
      }
      Write-Host "🕒 Time ended — shutting down session."

test: off

artifacts: off
